export const FETCHDATAREQUEST = "FETCHDATAREQUEST";
export const FETCHDATASUCCESS = "FETCHDATASUCCESS";
export const FETCHDATAERROR = "FETCHDATAERROR";

export const FETCHARCHIVEDATAREQUEST = "FETCHARCHIVEDATAREQUEST";
export const FETCHARCHIVEDATASUCCESS = "FETCHARCHIVEDATASUCCESS";
export const FETCHARCHIVEDATAERROR = "FETCHARCHIVEDATERROR";

export const FETCHMOSTREADREQUEST = "FETCHMOSTREADREQUEST";
export const FETCHMOSTREADSUCCESS = "FETCHMOSTREADSUCCESS";
export const FETCHMOSTREADERROR = "FETCHMOSTREADERROR";

export const FETCH_HEATLH_DATA_REQUEST = "FETCH_HEALTH_DATA_REQUEST";
export const FETCH_HEATLH_DATA_SUCCESS = "FETCH_HEALTH_DATA_SUCCESS"
export const FETCH_HEATLH_DATA_ERROR = "FETCH_HEALTH_DATA_ERROR";

export const FETCH_ENT_DATA_REQUEST = "FETCH_ENT_DATA_REQUEST";
export const FETCH_ENT_DATA_SUCCESS = "FETCH_ENT_DATA_SUCCESS"
export const FETCH_ENT_DATA_ERROR = "FETCH_ENT_DATA_ERROR";

export const FETCH_SPORTS_DATA_REQUEST = "FETCH_SPORTS_DATA_REQUEST";
export const FETCH_SPORTS_DATA_SUCCESS = "FETCH_SPORTS_DATA_SUCCESS"
export const FETCH_SPORTS_DATA_ERROR = "FETCH_SPORTS_DATA_ERROR";

export const FETCH_WORLD_DATA_REQUEST = "FETCH_WORLD_DATA_REQUEST";
export const FETCH_WORLD_DATA_SUCCESS = "FETCH_WORLD_DATA_SUCCESS"
export const FETCH_WORLD_DATA_ERROR = "FETCH_WORLD_DATA_ERROR";

export const FETCH_INDIA_DATA_REQUEST = "FETCH_INDIA_DATA_REQUEST";
export const FETCH_INDIA_DATA_SUCCESS = "FETCH_INDIA_DATA_SUCCESS"
export const FETCH_INDIA_DATA_ERROR = "FETCH_INDIA_DATA_ERROR";

export const FETCH_TECH_DATA_REQUEST = "FETCH_TECH_DATA_REQUEST";
export const FETCH_TECH_DATA_SUCCESS = "FETCH_TECH_DATA_SUCCESS"
export const FETCH_TECH_DATA_ERROR = "FETCH_TECH_DATA_ERROR";

export const FETCH_CRICKET_DATA_REQUEST = "FETCH_CRICKET_DATA_REQUEST";
export const FETCH_CRICKET_DATA_SUCCESS = "FETCH_CRICKET_DATA_SUCCESS"
export const FETCH_CRICKET_DATA_ERROR = "FETCH_CRICKET_DATA_ERROR";

export const FETCH_POLITICS_DATA_REQUEST = "FETCH_POLITICS_DATA_REQUEST";
export const FETCH_POLITICS_DATA_SUCCESS = "FETCH_POLITICS_DATA_SUCCESS"
export const FETCH_POLITICS_DATA_ERROR = "FETCH_POLITICS_DATA_ERROR";

export const FETCH_RANDOM_DATA_REQUEST = "FETCH_RANDOM_DATA_REQUEST";
export const FETCH_RANDOM_DATA_SUCCESS = "FETCH_RANDOM_DATA_SUCCESS"
export const FETCH_RANDOM_DATA_ERROR = "FETCH_RANDOM_DATA_ERROR";

export const FETCH_SEARCH_DATA_REQUEST = "FETCH_SEARCH_DATA_REQUEST";
export const FETCH_SEARCH_DATA_SUCCESS = "FETCH_SEARCH_DATA_SUCCESS"
export const FETCH_SEARCH_DATA_ERROR = "FETCH_SEARCH_DATA_ERROR";